# what is numpy 
* python library in which used for mathematical computational caculation 

. Array 
. matrix
. vectors 
. Tensor

1. how to install
!pip install numpy  

In [5]:

%pip install numpy
 

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

# create a array using numpy 
arr = np.array([1,2,3,4])
arr1 = np.array([2,12,23,34])
arr+arr1

array([ 3, 14, 26, 38])

In [7]:
# boolean index in numpy operator for using boolean condition

arr = np.array([1,2,3,4])
arr1 = np.array([2,1,23,34])

print(arr > 5)
arr1> 5


[False False False False]


array([False, False,  True,  True])

In [8]:
arr1[arr1 > 5]

array([23, 34])

In [9]:
# logical operator ar used ot perfoprm a operation in arr 
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8] )

print(arr1[arr1 % 2 == 0])
print(arr2[arr2 % 2 == 0])

[2 4]
[6 8]


In [10]:
print(arr1[np.logical_and((arr1 % 2== 0), (arr2 % 2 == 0))])
print(arr2[np.logical_or((arr1 % 2== 0), (arr2 % 2 == 0))])
print(arr2[np.logical_and((arr1 % 2== 0), (arr2 % 2 == 0))])

[2 4]
[6 8]
[6 8]


In [11]:
# sqaure  root

a = np.array([4,16,25,36])
np.sqrt(a)

array([2., 4., 5., 6.])

In [12]:
# 
print(np.sin(a))
print(np.cos(a))
print(np.sum(a))
print(np.tanh(a))
print(np.tan(a))



[-0.7568025  -0.28790332 -0.13235175 -0.99177885]
[-0.65364362 -0.95765948  0.99120281 -0.12796369]
81
[0.9993293 1.        1.        1.       ]
[ 1.15782128  0.30063224 -0.13352641  7.75047091]


In [13]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(matrix)
print(np.sum(matrix))
print(np.sum(matrix, axis=0))
print(np.sum(matrix, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]


In [14]:
mat = np.array([
    [9,10,11],
    [12,13,14],
    [15,16,17]
])

print(matrix+mat)
print()
print(np.dot(matrix,mat))

print()
print(np.subtract(matrix,mat))

[[10 12 14]
 [16 18 20]
 [22 24 26]]

[[ 78  84  90]
 [186 201 216]
 [294 318 342]]

[[-8 -8 -8]
 [-8 -8 -8]
 [-8 -8 -8]]


In [15]:
arr = np.array([[1],[2],[3]])
print(arr.T)
print(arr.shape)
print(arr.T.shape)

[[1 2 3]]
(3, 1)
(1, 3)


In [16]:
print(arr.shape)

print(arr.size)
print(arr.ndim)
print(arr.dtype)
print(arr.reshape)

# print(arr.flags)
print(arr.flatten)
print(arr.ravel)
print(arr.copy)
print(arr.view)

(3, 1)
3
2
int64
<built-in method reshape of numpy.ndarray object at 0x00000252FCB6A8B0>
<built-in method flatten of numpy.ndarray object at 0x00000252FCB6A8B0>
<built-in method ravel of numpy.ndarray object at 0x00000252FCB6A8B0>
<built-in method copy of numpy.ndarray object at 0x00000252FCB6A8B0>
<built-in method view of numpy.ndarray object at 0x00000252FCB6A8B0>


In [17]:
print(arr.dtype)

int64


In [18]:
arr = np.array([1,2,3,4,5,6])

print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [19]:
print(arr.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [20]:
arr = np.array([
    [1,2],
    [3,4]
])

x = arr.flatten()
print(x)

[1 2 3 4]


In [21]:
x = arr.ravel()
print(x)

[1 2 3 4]


In [22]:
b = arr.copy()
b

array([[1, 2],
       [3, 4]])

In [23]:
b = arr.copy()

b[0] = 100

print(arr)
print(b)

[[1 2]
 [3 4]]
[[100 100]
 [  3   4]]


In [24]:
b = arr.view()
b

array([[1, 2],
       [3, 4]])

In [25]:
arr = np.array([x for x in range(1,11)])

print(arr.reshape(2,5))

print(arr.reshape(5,2))

print(arr.reshape(10))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
num = np.arange(1,19)
print(num.reshape(3,6))
print(num.reshape(6,3))
print(num.reshape(2,9))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]


In [27]:
# mathematical function
# statistical function
# Aggregation method
# Copy vs View 
# Array Manipulation

In [ ]:
# only hAVE CREATE one value in hole metrci 
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
# zero eelements using np.zeroes

np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [31]:
# eye metrci it create eye 

np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
# create randomly module to create random mketric=x numbers 
np.random.rand(3,3)

array([[0.14782983, 0.26684245, 0.07082058],
       [0.57395034, 0.37354372, 0.70274359],
       [0.98906326, 0.73212204, 0.79233815]])

In [39]:
# create randomly module to create random mketric=x numbers 
np.random.seed(42)
np.random.randint(1,20,30)

array([ 7, 15, 11,  8,  7, 19, 11, 11,  4,  8,  3,  2, 12,  6,  2,  1, 12,
       12, 17, 10, 16, 15, 15, 19, 12,  3,  5, 19,  7,  9], dtype=int32)

In [36]:
np.random.randint(1,20,30).reshape(6,5)

array([[ 7, 13, 12,  4, 13],
       [15, 11,  9, 16,  5],
       [12, 14,  3,  8, 15],
       [17,  6,  5,  5, 14],
       [10, 17, 14, 10,  2],
       [ 6,  6,  9,  2,  4]], dtype=int32)

In [38]:
np.random.seed(42)

In [41]:
# commuative sum of the array 
arr = np.arange(1,5)
np.cumsum(arr)

array([ 1,  3,  6, 10])

In [42]:
# commuative product of the array 
arr = np.arange(1,5)
np.cumprod(arr)

array([ 1,  2,  6, 24])

### Array Manupulation
1. oncatenation
2. Vstacking
3. Horizontal


In [44]:
a = np.array([1,2,3,5])
b = np.array([6,7,8,9])
np.concatenate((a,b),axis=0)

array([1, 2, 3, 5, 6, 7, 8, 9])

In [47]:
# horizontalily stack 
mat1 = np.array([
    [1,2],
    [3,4]
])

mat2 = np.array([
    [5,6],
    [7,8]
])


np.hstack((mat1,mat2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [46]:

# verticaly stack
mat1 = np.array([
    [1,2],
    [3,4]
])

mat2 = np.array([
    [5,6],
    [7,8]
])


np.vstack((mat1,mat2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [56]:
# array slicing in numpy 

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

arr1 = np.array([1,2,3,4,5,6])

arr[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [60]:
arr[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [61]:
arr[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [63]:
arr[[0,1,2]]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Vectorization and Broadcasting
* Vectorization

"Vectorization is the process of applying operations on an entire NumPy array at once without explicitly using Python loops, resulting in faster and more memory-efficient computation."


* What is Broadcasting?

Broadcasting ka matlab hai:

Different shapes wale arrays ko compatible bana kar arithmetic operations perform karna.

NumPy automatically smaller array ko larger array ke size ke according expand kar deta hai.

"Automatically expanding smaller arrays so arithmetic operations can be performed between arrays of different but compatible shapes."

In [64]:
a = [1,2,3,4,5]
b = [10,20,30,40,50]

result = []

for i in range(len(a)):
    result.append(a[i] + b[i])

print(result)

[11, 22, 33, 44, 55]


In [65]:
# NumPy Vectorization
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([10,20,30,40,50])

result = a + b

print(result)

[11 22 33 44 55]


In [66]:
# addition 
arr = np.array([1,2,3])

print(arr + 10)

[11 12 13]


In [67]:
# Multiplication
arr = np.array([1,2,3])

print(arr * 5)

[ 5 10 15]


In [68]:
# Square
arr = np.array([1,2,3])

print(arr ** 2)

[1 4 9]


In [69]:
arr = np.array([1,2,3])

print(arr + 10)

[11 12 13]


In [70]:
# Row Vector Broadcasting
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20,30])

print(a + b)

[[11 22 33]
 [14 25 36]]


In [71]:
# Column Broadcasting
a = np.array([[1],
              [2],
              [3]])

b = np.array([10,20,30])

print(a+b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]
