## 1. Array Creation
. Create a NumPy array containing numbers from 1 to 20.

. Create an array of 15 zeros.

. Create an array of 10 ones.

. Create an array of even numbers between 2 and 50.

. Create an array of odd numbers between 1 and 50.

. Create a 3×3 matrix lled with 7.

. Create a 5×5 identity matrix.

. Generate 20 equally spaced values between 0 and 100


In [1]:
# 1 
import  numpy as np

arr = np.arange(1,20)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [5]:
#2 
zeros = np.zeros((3,5))
print(zeros)

arr = np.zeros(15, dtype=int)
arr

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
# . Create an array of 10 ones
arr = np.ones(10, dtype=int)
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [10]:
#. Create an array of even numbers between 2 and 50.
arr = np.array([x for x in range(2,50) if x % 2 ==0])
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [11]:
arr = np.arange(2, 50, 2)   # start=2, stop=51, step=2
print(arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [12]:
# . Create an array of odd numbers between 1 and 50.

odd = np.array([x for x in range(1,50) if x % 2 != 0])
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [14]:
#. Create a 3×3 matrix lled with 7.
arr = np.array((3,3))
arr

array([3, 3])

In [15]:
matrix = np.full((3,3),7)
matrix

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [19]:
# . Create a 5×5 identity matrix.

identity_matrix = np.eye(5,dtype=int)
identity_matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [22]:
matrix  = np.identity(5,dtype=int)
matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [24]:
arr = np.arange(0,100,20)
arr

array([ 0, 20, 40, 60, 80])

In [29]:

arr =  np.linspace(0,100,20)
arr

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

### 2. Array Attributes
. Create a 4×5 array and print:
shape
size
ndim
dtype

. Find the total number of elements in a 6×7 array.

. Convert an integer array into a oat array

In [31]:
arr = np.random.randint(1,100,size=(4,5))
arr

array([[72, 49, 74, 75, 54],
       [81, 24, 98, 50, 52],
       [75, 44, 54, 19, 54],
       [43, 82, 68, 22,  6]], dtype=int32)

In [34]:
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(4, 5)
20
2
int32


In [35]:
arr = np.random.randint(1,100,size=(6,7))
arr.size

42

In [37]:
arr_float = arr.astype(float)
arr_float

array([[ 4., 44.,  5., 43.,  7., 43.,  7.],
       [81., 29., 38., 39., 96., 59., 30.],
       [56., 16., 92., 37., 11., 54.,  5.],
       [ 4., 60., 54., 23., 24., 80., 28.],
       [52., 19., 22., 50.,  5., 36., 31.],
       [58., 26., 56., 16., 55., 95., 58.]])

### 3. Reshaping
. Create an array from 1 to 12 and reshape it into:
3×4
2×6
4×3

. Flatten a 3×4 matrix into a 1D array.

. Convert a 1D array of 16 elements into a 4×4 matrix

In [44]:
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [45]:
print(arr.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [46]:
arr_2x6 = arr.reshape(2, 6)
print(arr_2x6)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [47]:
arr_4x3 = arr.reshape(4, 3)
print(arr_4x3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [49]:
flat = arr.flatten()
print(flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
arr16 = np.arange(1, 17)   
matrix_4x4 = arr16.reshape(4, 4)
print(matrix_4x4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### 4. Indexing and Slicing

15. From an array containing numbers 1–20:

Extract rst 5 elements
Extract last 5 elements
Extract elements from index 5 to 15

16. From a 5×5 matrix:

Extract the rst row
Extract the last column
Extract the center element

17. Print all corner elements of a matrix.

18. Extract a 2×2 submatrix from a 4×4 matrix

In [56]:
arr = np.arange(1,20)
print(arr)
print(arr[:5])
print(arr[-5:])
print(arr[4:15])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 2 3 4 5]
[15 16 17 18 19]
[ 5  6  7  8  9 10 11 12 13 14 15]


In [58]:
arr = np.random.randint(1,26,size=(5,5))
print(arr)

[[ 3 19  5 16  1]
 [14 18 21  3 18]
 [ 7 19  3 19 17]
 [11 15 12 12 17]
 [ 5  5 25 10 23]]


In [70]:
print(arr[0,])
print(arr[0,:])
print(arr[:,4])
print(arr[:,-1])
print(arr[2,2])

[ 3 19  5 16  1]
[ 3 19  5 16  1]
[ 1 18 17 17 23]
[ 1 18 17 17 23]
3


In [71]:
corners = [matrix[0,0], matrix[0,-1], matrix[-1,0], matrix[-1,-1]]
print("Corner elements:", corners)


Corner elements: [np.int64(1), np.int64(0), np.int64(0), np.int64(1)]


In [72]:
matrix4 = np.arange(1, 17).reshape(4, 4)
print(matrix4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [74]:
submatrix = matrix4[0:2, 0:2]   # rows 1–2, cols 1–2
print(submatrix)


[[1 2]
 [5 6]]


### 5. Boolean Masking

. From an array of numbers 1–50, print all numbers greater than 25.

. Print all even numbers using boolean indexing.

. Replace all negative numbers with 0.

. Find numbers divisible by both 3 and 5.

In [80]:
arr = np.arange(1,51)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [81]:
arr = [x for x in arr if x > 25 ]
arr


[np.int64(26),
 np.int64(27),
 np.int64(28),
 np.int64(29),
 np.int64(30),
 np.int64(31),
 np.int64(32),
 np.int64(33),
 np.int64(34),
 np.int64(35),
 np.int64(36),
 np.int64(37),
 np.int64(38),
 np.int64(39),
 np.int64(40),
 np.int64(41),
 np.int64(42),
 np.int64(43),
 np.int64(44),
 np.int64(45),
 np.int64(46),
 np.int64(47),
 np.int64(48),
 np.int64(49),
 np.int64(50)]

In [83]:
arr = np.arange(1, 51)   # numbers from 1 to 50
print("Original array:", arr)

greater_25 = arr[arr > 25]
print("Numbers greater than 25:", greater_25)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
Numbers greater than 25: [26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50]


In [85]:
arr = np.arange(1, 51)   # numbers from 1 to 50
print("Original array:", arr)

even_arr = arr[arr % 2 == 0]
print("Even array ", even_arr)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
Even array  [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [90]:
arr = np.array([10, -5, 7, -3, 0, -8, 15])
arr[arr < 0] = 0
print("After replacing negatives:", arr)

After replacing negatives: [10  0  7  0  0  0 15]


In [91]:
arr = np.arange(1, 51)   # Numbers 1–50
divisible = arr[(arr % 3 == 0) & (arr % 5 == 0)]
divisible

array([15, 30, 45])

### 6. Mathematical Operations

. Add two arrays element-wise.

. Multiply two arrays element-wise.

. Find square of every element.

. Find cube of every element.

. Compute square root of all elements.

. Find exponential value of each element

In [99]:
a = np.array([1,2,3,4,5])
b  = np.array([6,7,8,9,10])

sums = a + b
print(sums)



[ 7  9 11 13 15]


In [100]:
multiply = a * b
print("Multiplication:", multiply)


Multiplication: [ 6 14 24 36 50]


In [101]:
square = a ** 2
print("Square:", square)


Square: [ 1  4  9 16 25]


In [102]:
cube = a ** 3
print("Cube:", cube)


Cube: [  1   8  27  64 125]


In [103]:
sqrt = np.sqrt(a)
print("Square root:", sqrt)


Square root: [1.         1.41421356 1.73205081 2.         2.23606798]


In [104]:
exp = np.exp(a)
print("Exponential:", exp)


Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


### 7. Aggregation Functions

29. Find:
sum
mean
median
min
max

30. Find the row-wise sum of a matrix.

31. Find the column-wise mean of a matrix.

32. Find the standard deviation of an array.

33. Find the variance of an array

In [107]:
arr= np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.min(arr))
print(np.max(arr))

15
3.0
3.0
1
5


In [112]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(np.sum(a,axis=1))
print(np.mean(a,axis=0))
print(np.std(a))
print(np.var(a))

[ 6 15 24]
[4. 5. 6.]
2.581988897471611
6.666666666666667


### 8. Broadcasting

34. Add 10 to every element of a matrix without using loops.

35. Multiply every row of a matrix by 2.

36. Given:

        arr = np.array([[1],[2],[3]]) 

        b = np.array([10,20,30]) 

    Find the resulting matrix after addition.

37. Create a multiplication table from 1 to 10 using broadcasting only.

In [115]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr)
print()
arr1 = arr+10
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [116]:
arr1 = arr*2
print(arr1)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [117]:
arr = np.array([[1],[2],[3]]) 
b = np.array([10,20,30])

result = arr + b
print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [120]:
arr = np.arange(1,11)
table = arr*10
table

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [121]:
x = np.arange(1, 11).reshape(10, 1)   # column vector
y = np.arange(1, 11)                  # row vector

table = x * y
print(table)


[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [123]:
x = np.arange(1, 11).reshape(10, 1)
x
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 9. Sorting and Searching

38. Sort an array in ascending order.

39. Find the indices of elements greater than 50.

40. Find the position of the maximum and minimum element

In [124]:
arr = np.array([1,5,2,3,6,10,8])
print(np.sort(arr))

[ 1  2  3  5  6  8 10]


In [125]:
arr = np.array([10, 20, 55, 60, 30, 75])
indices = np.where(arr > 50)
print("Indices of elements > 50:", indices)
print("Values:", arr[indices])


Indices of elements > 50: (array([2, 3, 5]),)
Values: [55 60 75]


In [126]:
arr = np.array([10, 20, 55, 60, 30, 75])

max_pos = np.argmax(arr)   # index of max element
min_pos = np.argmin(arr)   # index of min element

print("Max element position:", max_pos, "Value:", arr[max_pos])
print("Min element position:", min_pos, "Value:", arr[min_pos])


Max element position: 5 Value: 75
Min element position: 0 Value: 10
